# Form implementation generated from reading ui file 'C:\Users\-admin-\PycharmProjects\PythonProject\AppointmentSystem\Login\PatientUI.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(900, 529)
        Login.setStyleSheet("QMainWindow {\n"
                            "    background-color: #8E9498;\n"
                            "}\n"
                            "#centralwidget {\n"
                            "    background-color: #8E9498;\n"
                            "}\n"
                            "")
        self.centralwidget = QtWidgets.QWidget(parent=Login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(5, -10, 151, 111))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("images/logoremover.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(35, 40, 131, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        self.label_8.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(540, 40, 75, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
                                        "    border: none;\n"
                                        "    background-color: transparent; /* Makes the background clear */\n"
                                        "/* Optional: Makes it look like a link */\n"
                                        "    color: White; /* Optional: Changes text color to blue like a link */\n"
                                        "}\n"
                                        "\n"
                                        "/* Optional: Style for when the mouse is hovering over the button */\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: #BF94E4;\n"
                                        " /* Darker green on hover */\n"
                                        "}\n"
                                        "")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(640, 40, 75, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
                                        "    border: none;\n"
                                        "    background-color: transparent; /* Makes the background clear */\n"
                                        "/* Optional: Makes it look like a link */\n"
                                        "    color: White; /* Optional: Changes text color to blue like a link */\n"
                                        "}\n"
                                        "\n"
                                        "/* Optional: Style for when the mouse is hovering over the button */\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: #BF94E4; /* Darker green on hover */\n"
                                        "}\n"
                                        "")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(740, 40, 75, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
                                        "    border: none;\n"
                                        "    background-color: transparent; /* Makes the background clear */\n"
                                        "/* Optional: Makes it look like a link */\n"
                                        "    color: White; /* Optional: Changes text color to blue like a link */\n"
                                        "}\n"
                                        "\n"
                                        "/* Optional: Style for when the mouse is hovering over the button */\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: #BF94E4; /* Darker green on hover */\n"
                                        "}\n"
                                        "")
        self.pushButton_6.setObjectName("pushButton_6")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(-20, 0, 921, 541))
        self.stackedWidget.setStyleSheet("QStackedWidget > QWidget {\n"
                                         "    background-color: #8E9498;\n"
                                         "}\n"
                                         "")
        self.stackedWidget.setObjectName("stackedWidget")
        self.NewAppointment = QtWidgets.QWidget()
        self.NewAppointment.setObjectName("NewAppointment")
        self.frame = QtWidgets.QFrame(parent=self.NewAppointment)
        self.frame.setGeometry(QtCore.QRect(20, 90, 151, 441))
        self.frame.setStyleSheet("\n"
                                 "background-color: rgb(217, 219, 221);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_6 = QtWidgets.QLabel(parent=self.frame)
        self.label_6.setGeometry(QtCore.QRect(5, -10, 151, 111))
        self.label_6.setText("")
        # Add this line after creating the label or in your initialization method
        self.label_5.hide()
        self.label_6.setPixmap(QtGui.QPixmap(":/images/logoremover.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.NewAppointmentbutton = QtWidgets.QPushButton(parent=self.frame)
        self.NewAppointmentbutton.setGeometry(QtCore.QRect(0, 90, 151, 41))
        self.NewAppointmentbutton.setStyleSheet("/* Base style for the button */\n"
                                                "QPushButton {\n"
                                                "    /* Make the button transparent by default */\n"
                                                "  background-color: #D3D3D3; /* The light grey color from the picture */\n"
                                                "    color: black;              /* Keeps the text black */\n"
                                                "    /* Adjust border-radius to match the full rounding in the image */\n"
                                                "    border-radius: 15px;       \n"
                                                "}\n"
                                                "/* The style to use when the button is the active page (the \"checked\" state) */\n"
                                                "")
        self.NewAppointmentbutton.setCheckable(True)
        self.NewAppointmentbutton.setChecked(False)
        self.NewAppointmentbutton.setObjectName("NewAppointmentbutton")
        self.Logoutbutton = QtWidgets.QPushButton(parent=self.frame)
        self.Logoutbutton.setGeometry(QtCore.QRect(0, 410, 151, 23))
        self.Logoutbutton.setStyleSheet("QPushButton {\n"
                                        "    background-color: transparent;\n"
                                        "    border: none;\n"
                                        "    color: red;\n"
                                        "}")
        self.Logoutbutton.setObjectName("Logoutbutton")
        self.MyAppointmentbutton = QtWidgets.QPushButton(parent=self.frame)
        self.MyAppointmentbutton.setGeometry(QtCore.QRect(0, 150, 151, 41))
        self.MyAppointmentbutton.setStyleSheet("/* Base style for the button */\n"
                                               "QPushButton {\n"
                                               "    /* Make the button transparent by default */\n"
                                               "  background-color: transparent; /* The light grey color from the picture */\n"
                                               "    color: black;              /* Keeps the text black */\n"
                                               "    /* Adjust border-radius to match the full rounding in the image */\n"
                                               "    border-radius: 15px;       \n"
                                               "}\n"
                                               "/* The style to use when the button is the active page (the \"checked\" state) */\n"
                                               "")
        self.MyAppointmentbutton.setCheckable(True)
        self.MyAppointmentbutton.setChecked(False)
        self.MyAppointmentbutton.setObjectName("MyAppointmentbutton")
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_13.setGeometry(QtCore.QRect(0, 210, 151, 41))
        self.pushButton_13.setStyleSheet("/* Base style for the button */\n"
                                         "QPushButton {\n"
                                         "    /* Make the button transparent by default */\n"
                                         "  background-color: #transparent; /* The light grey color from the picture */\n"
                                         "    color: black;              /* Keeps the text black */\n"
                                         "    /* Adjust border-radius to match the full rounding in the image */\n"
                                         "    border-radius: 15px;       \n"
                                         "}\n"
                                         "/* The style to use when the button is the active page (the \"checked\" state) */\n"
                                         "")
        self.pushButton_13.setCheckable(True)
        self.pushButton_13.setChecked(False)
        self.pushButton_13.setObjectName("pushButton_13")
        self.frame_2 = QtWidgets.QFrame(parent=self.NewAppointment)
        self.frame_2.setGeometry(QtCore.QRect(170, 90, 751, 441))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.dateEdit = QtWidgets.QDateEdit(parent=self.frame_2)
        self.dateEdit.setGeometry(QtCore.QRect(50, 30, 271, 62))
        self.dateEdit.setStyleSheet("/* Date Edit Main Widget */\n"
                                    "QDateEdit {\n"
                                    "    background-color: white;\n"
                                    "    border: 1px solid #D1D5DB;\n"
                                    "    border-radius: 8px;\n"
                                    "    padding: 10px 12px 10px 60px; \n"
                                    "    font-size: 14px;\n"
                                    "    min-height: 40px;\n"
                                    "    color: #374151;\n"
                                    "    selection-background-color: #3B82F6;\n"
                                    "    selection-color: white;\n"
                                    "}\n"
                                    "\n"
                                    "QDateEdit::drop-down {\n"
                                    "    subcontrol-origin: padding;\n"
                                    "    subcontrol-position: top right;\n"
                                    "    border-left: 1px solid #D1D5DB;\n"
                                    "    width: 40px; /* Increased from 30px */\n"
                                    "    border-radius: 0 8px 8px 0;\n"
                                    "}\n"
                                    "\n"
                                    "QDateEdit::down-arrow {\n"
                                    "    image: url(images/calendar.png);\n"
                                    "    width: 24px; /* Increased from 16px */\n"
                                    "    height: 24px; /* Increased from 16px */\n"
                                    "}\n"
                                    "\n"
                                    "/* Calendar Widget Styling */\n"
                                    "QCalendarWidget {\n"
                                    "    border: 1px solid #E5E7EB;\n"
                                    "    border-radius: 8px;\n"
                                    "    background-color: white;\n"
                                    "}\n"
                                    "\n"
                                    "QCalendarWidget QToolButton {\n"
                                    "    color: #374151;\n"
                                    "    background-color: #F3F4F6;\n"
                                    "    border-radius: 6px;\n"
                                    "    padding: 4px 8px;\n"
                                    "    font-weight: bold;\n"
                                    "}\n"
                                    "\n"
                                    "QCalendarWidget QMenu {\n"
                                    "    background-color: white;\n"
                                    "    border: 1px solid #E5E7EB;\n"
                                    "    border-radius: 6px;\n"
                                    "}\n"
                                    "\n"
                                    "QCalendarWidget QWidget#qt_calendar_navigationbar {\n"
                                    "    background-color: #F9FAFB;\n"
                                    "    border-radius: 8px 8px 0 0;\n"
                                    "}\n"
                                    "\n"
                                    "QCalendarWidget QAbstractItemView:enabled {\n"
                                    "    color: #374151;\n"
                                    "    background-color: white;\n"
                                    "    selection-background-color: #3B82F6;\n"
                                    "    selection-color: white;\n"
                                    "}")
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2025, 1, 1), QtCore.QTime(8, 0, 0)))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.timeEdit_2 = QtWidgets.QTimeEdit(parent=self.frame_2)
        self.timeEdit_2.setGeometry(QtCore.QRect(390, 30, 271, 62))
        self.timeEdit_2.setStyleSheet("/* Time Edit with Clock Icon */\n"
                                      "QTimeEdit {\n"
                                      "    background-color: white;\n"
                                      "    border: 1px solid #D1D5DB;\n"
                                      "    border-radius: 8px;\n"
                                      "    padding: 10px 12px 10px 80px;\n"
                                      "    font-size: 14px;\n"
                                      "    min-height: 40px;\n"
                                      "    color: #374151;\n"
                                      "    selection-background-color: #3B82F6;\n"
                                      "    selection-color: white;\n"
                                      "    background-repeat: no-repeat;\n"
                                      "    background-position: 12px center;\n"
                                      "    background-origin: content-box;\n"
                                      "}\n"
                                      "\n"
                                      "QTimeEdit:hover {\n"
                                      "    border-color: #9CA3AF;\n"
                                      "}\n"
                                      "\n"
                                      "QTimeEdit:focus {\n"
                                      "    border: 2px solid #3B82F6;\n"
                                      "    padding: 9px 11px 9px 39px;\n"
                                      "    background-position: 11px center;\n"
                                      "}\n"
                                      "\n"
                                      "/* Button adjustments with icon */\n"
                                      "QTimeEdit::up-button {\n"
                                      "     subcontrol-origin: padding;\n"
                                      "    subcontrol-position: top right;\n"
                                      "    width: 30px;\n"
                                      "    border-left: 1px solid #D1D5DB;\n"
                                      "    border-radius: 0 0 8px 0;\n"
                                      "    background-color: transparent;\n"
                                      "}\n"
                                      "\n"
                                      "QTimeEdit::down-button {\n"
                                      "    subcontrol-origin: padding;\n"
                                      "    subcontrol-position: bottom right;\n"
                                      "    width: 30px;\n"
                                      "    border-left: 1px solid #D1D5DB;\n"
                                      "    border-radius: 0 0 8px 0;\n"
                                      "    background-color: transparent;\n"
                                      "}\n"
                                      "\n"
                                      "\n"
                                      "/* Add these to your stylesheet */\n"
                                      "QTimeEdit::up-arrow {\n"
                                      "    image: url(images/uparrow.png);  /* Put your up arrow PNG here */\n"
                                      "    width: 16px;\n"
                                      "    height: 16px;\n"
                                      "}\n"
                                      "\n"
                                      "QTimeEdit::down-arrow {\n"
                                      "    image: url(images/downarrow.png) ;  /* Put your down arrow PNG here */\n"
                                      "    width: 16px;\n"
                                      "    height: 16px;\n"
                                      "} \n"
                                      "")
        self.timeEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(8, 0, 0)))
        self.timeEdit_2.setCalendarPopup(False)
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.frameDrLevi = QtWidgets.QFrame(parent=self.frame_2)
        self.frameDrLevi.setGeometry(QtCore.QRect(50, 120, 271, 201))
        self.frameDrLevi.setStyleSheet("/* Doctor frames */\n"
                                       "QFrame#frameDrLevi, QFrame#frameDrChancee {\n"
                                       "    background-color: white;\n"
                                       "    border: 1px solid #D1D5DB;\n"
                                       "    border-radius: 8px;\n"
                                       "    padding: 12px;\n"
                                       "    margin-bottom: 8px;\n"
                                       "}\n"
                                       "\n"
                                       "/* Hover effect */\n"
                                       "QFrame#frameDrLevi:hover, QFrame#frameDrChancee:hover {\n"
                                       "    border-color: #3B82F6;\n"
                                       "    background-color: #F8FAFB;\n"
                                       "}\n"
                                       "\n"
                                       "/* Selected state - when radio button is checked */\n"
                                       "QFrame#frameDrLevi[selected=\"true\"], \n"
                                       "QFrame#frameDrChancee[selected=\"true\"] {\n"
                                       "    background-color: #E0F2FE;\n"
                                       "    border: 2px solid #3B82F6;\n"
                                       "}\n"
                                       "\n"
                                       "/* Picture style */\n"
                                       "QLabel#picDrLevi, QLabel#picDrChancee {\n"
                                       "    border-radius: 6px;\n"
                                       "}\n"
                                       "\n"
                                       "/* Text style - for ALL text labels starting with these names */\n"
                                       "QLabel[objectName^=\"textDrLevi\"],\n"
                                       "QLabel[objectName^=\"textDrChancee\"] {\n"
                                       "    color: #374151;\n"
                                       "    font-size: 14px;\n"
                                       "    line-height: 1.3;\n"
                                       "}\n"
                                       "\n"
                                       "/* More specific if you have different sizes */\n"
                                       "QLabel[objectName^=\"textDrLevi\"]:first-child,\n"
                                       "QLabel[objectName^=\"textDrChancee\"]:first-child {\n"
                                       "    color: #6B7280;\n"
                                       "    font-size: 12px;\n"
                                       "}\n"
                                       "\n"
                                       "QLabel[objectName^=\"textDrLevi\"]:nth-child(2),\n"
                                       "QLabel[objectName^=\"textDrChancee\"]:nth-child(2) {\n"
                                       "    color: #111827;\n"
                                       "    font-size: 16px;\n"
                                       "    font-weight: bold;\n"
                                       "}\n"
                                       "\n"
                                       "QLabel[objectName^=\"textDrLevi\"]:nth-child(3),\n"
                                       "QLabel[objectName^=\"textDrChancee\"]:nth-child(3) {\n"
                                       "    color: #6B7280;\n"
                                       "    font-size: 11px;\n"
                                       "}\n"
                                       "\n"
                                       "/* When selected, change ALL text colors */\n"
                                       "QFrame[selected=\"true\"] QLabel[objectName^=\"textDrLevi\"],\n"
                                       "QFrame[selected=\"true\"] QLabel[objectName^=\"textDrChancee\"] {\n"
                                       "    color: #0369A1;\n"
                                       "}\n"
                                       "\n"
                                       "/* More specific for selected state */\n"
                                       "QFrame[selected=\"true\"] QLabel[objectName^=\"textDrLevi\"]:first-child,\n"
                                       "QFrame[selected=\"true\"] QLabel[objectName^=\"textDrChancee\"]:first-child {\n"
                                       "    color: #0284C7; /* Slightly darker blue for specialty */\n"
                                       "}\n"
                                       "\n"
                                       "QFrame[selected=\"true\"] QLabel[objectName^=\"textDrLevi\"]:nth-child(2),\n"
                                       "QFrame[selected=\"true\"] QLabel[objectName^=\"textDrChancee\"]:nth-child(2) {\n"
                                       "    color: #0369A1; /* Blue for doctor name */\n"
                                       "    font-weight: bold;\n"
                                       "}\n"
                                       "\n"
                                       "QFrame[selected=\"true\"] QLabel[objectName^=\"textDrLevi\"]:nth-child(3),\n"
                                       "QFrame[selected=\"true\"] QLabel[objectName^=\"textDrChancee\"]:nth-child(3) {\n"
                                       "    color: #0EA5E9; /* Lighter blue for hours */\n"
                                       "}\n"
                                       "\n"
                                       "/* Radio button styling */\n"
                                       "QRadioButton::indicator {\n"
                                       "    width: 20px;\n"
                                       "    height: 20px;\n"
                                       "}\n"
                                       "\n"
                                       "QRadioButton::indicator:unchecked {\n"
                                       "    border: 2px solid #D1D5DB;\n"
                                       "    border-radius: 10px;\n"
                                       "}\n"
                                       "\n"
                                       "QRadioButton::indicator:checked {\n"
                                       "    border: 2px solid #3B82F6;\n"
                                       "    border-radius: 10px;\n"
                                       "    background-color: #3B82F6;\n"
                                       "}")
        self.frameDrLevi.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameDrLevi.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameDrLevi.setObjectName("frameDrLevi")
        self.textDrLevi_2 = QtWidgets.QLabel(parent=self.frameDrLevi)
        self.textDrLevi_2.setGeometry(QtCore.QRect(170, 80, 51, 51))
        self.textDrLevi_2.setObjectName("textDrLevi_2")
        self.textDrLevi = QtWidgets.QLabel(parent=self.frameDrLevi)
        self.textDrLevi.setGeometry(QtCore.QRect(170, 30, 41, 51))
        self.textDrLevi.setObjectName("textDrLevi")
        self.picDrLevi = QtWidgets.QLabel(parent=self.frameDrLevi)
        self.picDrLevi.setGeometry(QtCore.QRect(30, 30, 121, 131))
        self.picDrLevi.setAutoFillBackground(False)
        self.picDrLevi.setText("")
        self.picDrLevi.setPixmap(QtGui.QPixmap(":/images/doctor.png"))
        self.picDrLevi.setScaledContents(True)
        self.picDrLevi.setObjectName("picDrLevi")
        self.radioDrLevi = QtWidgets.QRadioButton(parent=self.frameDrLevi)
        self.radioDrLevi.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.radioDrLevi.setText("")
        self.radioDrLevi.setCheckable(True)
        self.radioDrLevi.setObjectName("radioDrLevi")
        self.frameDrChancee = QtWidgets.QFrame(parent=self.frame_2)
        self.frameDrChancee.setGeometry(QtCore.QRect(390, 120, 271, 201))
        self.frameDrChancee.setStyleSheet("/* Doctor frames */\n"
                                          "QFrame#frameDrLevi, QFrame#frameDrChancee {\n"
                                          "    background-color: white;\n"
                                          "    border: 1px solid #D1D5DB;\n"
                                          "    border-radius: 8px;\n"
                                          "    padding: 12px;\n"
                                          "    margin-bottom: 8px;\n"
                                          "}\n"
                                          "\n"
                                          "/* Hover effect */\n"
                                          "QFrame#frameDrLevi:hover, QFrame#frameDrChancee:hover {\n"
                                          "    border-color: #3B82F6;\n"
                                          "    background-color: #F8FAFB;\n"
                                          "}\n"
                                          "\n"
                                          "/* Selected state - when radio button is checked */\n"
                                          "QFrame#frameDrLevi[selected=\"true\"], \n"
                                          "QFrame#frameDrChancee[selected=\"true\"] {\n"
                                          "    background-color: #E0F2FE;\n"
                                          "    border: 2px solid #3B82F6;\n"
                                          "}\n"
                                          "\n"
                                          "/* Picture style */\n"
                                          "QLabel#picDrLevi, QLabel#picDrChancee {\n"
                                          "    border-radius: 6px;\n"
                                          "}\n"
                                          "\n"
                                          "/* Text style - for ALL text labels starting with these names */\n"
                                          "QLabel[objectName^=\"textDrLevi\"],\n"
                                          "QLabel[objectName^=\"textDrChancee\"] {\n"
                                          "    color: #374151;\n"
                                          "    font-size: 14px;\n"
                                          "    line-height: 1.3;\n"
                                          "}\n"
                                          "\n"
                                          "/* More specific if you have different sizes */\n"
                                          "QLabel[objectName^=\"textDrLevi\"]:first-child,\n"
                                          "QLabel[objectName^=\"textDrChancee\"]:first-child {\n"
                                          "    color: #6B7280;\n"
                                          "    font-size: 12px;\n"
                                          "}\n"
                                          "\n"
                                          "QLabel[objectName^=\"textDrLevi\"]:nth-child(2),\n"
                                          "QLabel[objectName^=\"textDrChancee\"]:nth-child(2) {\n"
                                          "    color: #111827;\n"
                                          "    font-size: 16px;\n"
                                          "    font-weight: bold;\n"
                                          "}\n"
                                          "\n"
                                          "QLabel[objectName^=\"textDrLevi\"]:nth-child(3),\n"
                                          "QLabel[objectName^=\"textDrChancee\"]:nth-child(3) {\n"
                                          "    color: #6B7280;\n"
                                          "    font-size: 11px;\n"
                                          "}\n"
                                          "\n"
                                          "/* When selected, change ALL text colors */\n"
                                          "QFrame[selected=\"true\"] QLabel[objectName^=\"textDrLevi\"],\n"
                                          "QFrame[selected=\"true\"] QLabel[objectName^=\"textDrChancee\"] {\n"
                                          "    color: #0369A1;\n"
                                          "}\n"
                                          "\n"
                                          "/* More specific for selected state */\n"
                                          "QFrame[selected=\"true\"] QLabel[objectName^=\"textDrLevi\"]:first-child,\n"
                                          "QFrame[selected=\"true\"] QLabel[objectName^=\"textDrChancee\"]:first-child {\n"
                                          "    color: #0284C7; /* Slightly darker blue for specialty */\n"
                                          "}\n"
                                          "\n"
                                          "QFrame[selected=\"true\"] QLabel[objectName^=\"textDrLevi\"]:nth-child(2),\n"
                                          "QFrame[selected=\"true\"] QLabel[objectName^=\"textDrChancee\"]:nth-child(2) {\n"
                                          "    color: #0369A1; /* Blue for doctor name */\n"
                                          "    font-weight: bold;\n"
                                          "}\n"
                                          "\n"
                                          "QFrame[selected=\"true\"] QLabel[objectName^=\"textDrLevi\"]:nth-child(3),\n"
                                          "QFrame[selected=\"true\"] QLabel[objectName^=\"textDrChancee\"]:nth-child(3) {\n"
                                          "    color: #0EA5E9; /* Lighter blue for hours */\n"
                                          "}\n"
                                          "\n"
                                          "/* Radio button styling */\n"
                                          "QRadioButton::indicator {\n"
                                          "    width: 20px;\n"
                                          "    height: 20px;\n"
                                          "}\n"
                                          "\n"
                                          "QRadioButton::indicator:unchecked {\n"
                                          "    border: 2px solid #D1D5DB;\n"
                                          "    border-radius: 10px;\n"
                                          "}\n"
                                          "\n"
                                          "QRadioButton::indicator:checked {\n"
                                          "    border: 2px solid #3B82F6;\n"
                                          "    border-radius: 10px;\n"
                                          "    background-color: #3B82F6;\n"
                                          "}")
        self.frameDrChancee.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameDrChancee.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameDrChancee.setObjectName("frameDrChancee")
        self.textDrChancee = QtWidgets.QLabel(parent=self.frameDrChancee)
        self.textDrChancee.setGeometry(QtCore.QRect(170, 80, 51, 51))
        self.textDrChancee.setObjectName("textDrChancee")
        self.textDrChancee_2 = QtWidgets.QLabel(parent=self.frameDrChancee)
        self.textDrChancee_2.setGeometry(QtCore.QRect(170, 30, 41, 51))
        self.textDrChancee_2.setObjectName("textDrChancee_2")
        self.picDrChancee = QtWidgets.QLabel(parent=self.frameDrChancee)
        self.picDrChancee.setGeometry(QtCore.QRect(30, 30, 121, 131))
        self.picDrChancee.setAutoFillBackground(False)
        self.picDrChancee.setText("")
        self.picDrChancee.setPixmap(QtGui.QPixmap(":/images/doctor.png"))
        self.picDrChancee.setScaledContents(True)
        self.picDrChancee.setObjectName("picDrChancee")
        self.radioDrChancee = QtWidgets.QRadioButton(parent=self.frameDrChancee)
        self.radioDrChancee.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.radioDrChancee.setText("")
        self.radioDrChancee.setCheckable(True)
        self.radioDrChancee.setObjectName("radioDrChancee")
        self.saveappointment = QtWidgets.QPushButton(parent=self.frame_2)
        self.saveappointment.setGeometry(QtCore.QRect(270, 330, 171, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(99, 88, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(99, 88, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(99, 88, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(99, 88, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(99, 88, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(99, 88, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(99, 88, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(99, 88, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(99, 88, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        self.saveappointment.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.saveappointment.setFont(font)
        self.saveappointment.setStyleSheet("QPushButton {\n"
                                           "    background-color: #6358DC;\n"
                                           "    border: none; /* Optional: Removes the default system border so the color shows fully */\n"
                                           "}\n"
                                           "QPushButton {\n"
                                           "    padding: 15px 32px; /* Add padding for a better size */\n"
                                           "    text-align: center;\n"
                                           "    text-decoration: none;\n"
                                           "    font-size: 10px;\n"
                                           "    margin: 4px 2px;\n"
                                           "    border-radius: 8px; /* Rounded corners */\n"
                                           "}\n"
                                           "QPushButton:hover {\n"
                                           "    background-color: #BF94E4; /* Darker green on hover */\n"
                                           "}\n"
                                           "")
        self.saveappointment.setObjectName("saveappointment")
        self.stackedWidget.addWidget(self.NewAppointment)
        self.MyAppointments = QtWidgets.QWidget()
        self.MyAppointments.setObjectName("MyAppointments")
        self.frame_4 = QtWidgets.QFrame(parent=self.MyAppointments)
        self.frame_4.setGeometry(QtCore.QRect(20, 90, 151, 441))
        self.frame_4.setStyleSheet("\n"
                                   "background-color: rgb(217, 219, 221);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_7.setGeometry(QtCore.QRect(5, -10, 151, 111))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/images/logoremover.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.NewAppointmentbutton_2 = QtWidgets.QPushButton(parent=self.frame_4)
        self.NewAppointmentbutton_2.setGeometry(QtCore.QRect(0, 90, 151, 41))
        self.NewAppointmentbutton_2.setStyleSheet("/* Base style for the button */\n"
                                                  "QPushButton {\n"
                                                  "    /* Make the button transparent by default */\n"
                                                  "  background-color: #transparent; /* The light grey color from the picture */\n"
                                                  "    color: black;              /* Keeps the text black */\n"
                                                  "    /* Adjust border-radius to match the full rounding in the image */\n"
                                                  "    border-radius: 15px;       \n"
                                                  "}\n"
                                                  "/* The style to use when the button is the active page (the \"checked\" state) */\n"
                                                  "")
        self.NewAppointmentbutton_2.setCheckable(True)
        self.NewAppointmentbutton_2.setChecked(False)
        self.NewAppointmentbutton_2.setObjectName("NewAppointmentbutton_2")
        self.LogOutButton = QtWidgets.QPushButton(parent=self.frame_4)
        self.LogOutButton.setGeometry(QtCore.QRect(0, 410, 151, 23))
        self.LogOutButton.setStyleSheet("QPushButton {\n"
                                        "    background-color: transparent;\n"
                                        "    border: none;\n"
                                        "    color: red;\n"
                                        "}")
        self.LogOutButton.setObjectName("LogOutButton")
        self.MyAppointmentButton = QtWidgets.QPushButton(parent=self.frame_4)
        self.MyAppointmentButton.setGeometry(QtCore.QRect(0, 150, 151, 41))
        self.MyAppointmentButton.setStyleSheet("/* Base style for the button */\n"
                                               "QPushButton {\n"
                                               "    /* Make the button transparent by default */\n"
                                               "  background-color: #D3D3D3; /* The light grey color from the picture */\n"
                                               "    color: black;              /* Keeps the text black */\n"
                                               "    /* Adjust border-radius to match the full rounding in the image */\n"
                                               "    border-radius: 15px;       \n"
                                               "}\n"
                                               "/* The style to use when the button is the active page (the \"checked\" state) */\n"
                                               "")
        self.MyAppointmentButton.setCheckable(True)
        self.MyAppointmentButton.setChecked(False)
        self.MyAppointmentButton.setObjectName("MyAppointmentButton")
        self.MyProfileButton = QtWidgets.QPushButton(parent=self.frame_4)
        self.MyProfileButton.setGeometry(QtCore.QRect(0, 210, 151, 41))
        self.MyProfileButton.setStyleSheet("/* Base style for the button */\n"
                                           "QPushButton {\n"
                                           "    /* Make the button transparent by default */\n"
                                           "  background-color: #transparent; /* The light grey color from the picture */\n"
                                           "    color: black;              /* Keeps the text black */\n"
                                           "    /* Adjust border-radius to match the full rounding in the image */\n"
                                           "    border-radius: 15px;       \n"
                                           "}\n"
                                           "/* The style to use when the button is the active page (the \"checked\" state) */\n"
                                           "")
        self.MyProfileButton.setCheckable(True)
        self.MyProfileButton.setChecked(False)
        self.MyProfileButton.setObjectName("MyProfileButton")

        # Fixed MyAppointments section with modern table
        self.frame_3 = QtWidgets.QFrame(parent=self.MyAppointments)
        self.frame_3.setGeometry(QtCore.QRect(170, 90, 751, 441))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.MyAppointments_3 = QtWidgets.QTableWidget(parent=self.frame_3)
        self.MyAppointments_3.setGeometry(QtCore.QRect(20, 60, 711, 361))
        self.MyAppointments_3.setObjectName("MyAppointments_3")
        self.MyAppointments_3.setColumnCount(3)
        self.MyAppointments_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.MyAppointments_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.MyAppointments_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.MyAppointments_3.setHorizontalHeaderItem(2, item)
        self.MyAppointments_3.horizontalHeader().setDefaultSectionSize(230)
        self.MyAppointments_3.horizontalHeader().setStretchLastSection(True)
        self.MyAppointments_3.verticalHeader().setVisible(False)

        # Modern table styling
        self.MyAppointments_3.setStyleSheet("""
            /* Modern Table Styling */
            QTableWidget {
                background-color: white;
                border: 1px solid #E5E7EB;
                border-radius: 8px;
                gridline-color: #F3F4F6;
                selection-background-color: #3B82F6;
                selection-color: white;
                outline: none;
                font-size: 14px;
            }

            /* Header Styling */
            QHeaderView::section {
                background-color: #F9FAFB;
                padding: 16px;
                border: none;
                border-right: 1px solid #E5E7EB;
                border-bottom: 2px solid #E5E7EB;
                font-weight: 600;
                font-size: 13px;
                color: #374151;
                text-transform: uppercase;
                letter-spacing: 0.5px;
            }

            QHeaderView::section:last {
                border-right: none;
            }

            /* Row Styling */
            QTableWidget::item {
                padding: 16px;
                border: none;
                border-bottom: 1px solid #F3F4F6;
                color: #374151;
            }

            QTableWidget::item:selected {
                background-color: #3B82F6;
                color: white;
            }

            /* Alternate Row Colors */
            QTableWidget::item:alternate {
                background-color: #F9FAFB;
            }

            /* Scrollbar Styling */
            QScrollBar:vertical {
                border: none;
                background-color: #F3F4F6;
                width: 12px;
                border-radius: 6px;
                margin: 0px;
            }

            QScrollBar::handle:vertical {
                background-color: #D1D5DB;
                border-radius: 6px;
                min-height: 30px;
            }

            QScrollBar::handle:vertical:hover {
                background-color: #9CA3AF;
            }

            QScrollBar::add-line:vertical, 
            QScrollBar::sub-line:vertical {
                border: none;
                background: none;
                height: 0px;
            }

            QScrollBar:horizontal {
                border: none;
                background-color: #F3F4F6;
                height: 12px;
                border-radius: 6px;
                margin: 0px;
            }

            QScrollBar::handle:horizontal {
                background-color: #D1D5DB;
                border-radius: 6px;
                min-width: 30px;
            }

            /* Status Badges */
            QTableWidget::item[status="confirmed"] {
                background-color: #D1FAE5;
                color: #059669;
                border-radius: 20px;
                padding: 6px 16px;
                font-weight: 600;
                font-size: 12px;
                text-align: center;
            }

            QTableWidget::item[status="pending"] {
                background-color: #FEF3C7;
                color: #D97706;
                border-radius: 20px;
                padding: 6px 16px;
                font-weight: 600;
                font-size: 12px;
                text-align: center;
            }

            QTableWidget::item[status="cancelled"] {
                background-color: #FEE2E2;
                color: #DC2626;
                border-radius: 20px;
                padding: 6px 16px;
                font-weight: 600;
                font-size: 12px;
                text-align: center;
            }
        """)

        self.stackedWidget.addWidget(self.MyAppointments)
        self.MyProfile = QtWidgets.QWidget()
        self.MyProfile.setObjectName("MyProfile")
        self.frame_6 = QtWidgets.QFrame(parent=self.MyProfile)
        self.frame_6.setGeometry(QtCore.QRect(170, 90, 751, 441))
        self.frame_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(parent=self.frame_6)
        self.lineEdit_7.setGeometry(QtCore.QRect(150, 90, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("QLineEdit {\n"
                                      "    background-color: #FFFFFF; /* White background */\n"
                                      "    border: 1px solid #CCCCCC; /* Light grey border */\n"
                                      "    border-radius: 10px; /* Rounded corners (adjust as needed) */\n"
                                      "    padding: 8px; /* Space inside the box so text isn\'t touching edges */\n"
                                      "    box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.2); /* Dropdown shadow */\n"
                                      "}\n"
                                      "\n"
                                      "QLineEdit:focus {\n"
                                      "    border: 1px solid #0078D7; /* Highlight border when clicked/focused */\n"
                                      "}\n"
                                      "")
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(parent=self.frame_6)
        self.lineEdit_8.setGeometry(QtCore.QRect(360, 90, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setStyleSheet("QLineEdit {\n"
                                      "    background-color: #FFFFFF; /* White background */\n"
                                      "    border: 1px solid #CCCCCC; /* Light grey border */\n"
                                      "    border-radius: 10px; /* Rounded corners (adjust as needed) */\n"
                                      "    padding: 8px; /* Space inside the box so text isn\'t touching edges */\n"
                                      "    box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.2); /* Dropdown shadow */\n"
                                      "}\n"
                                      "\n"
                                      "QLineEdit:focus {\n"
                                      "    border: 1px solid #0078D7; /* Highlight border when clicked/focused */\n"
                                      "}\n"
                                      "")
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(parent=self.frame_6)
        self.lineEdit_9.setGeometry(QtCore.QRect(150, 150, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setStyleSheet("QLineEdit {\n"
                                      "    background-color: #FFFFFF; /* White background */\n"
                                      "    border: 1px solid #CCCCCC; /* Light grey border */\n"
                                      "    border-radius: 10px; /* Rounded corners (adjust as needed) */\n"
                                      "    padding: 8px; /* Space inside the box so text isn\'t touching edges */\n"
                                      "    box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.2); /* Dropdown shadow */\n"
                                      "}\n"
                                      "\n"
                                      "QLineEdit:focus {\n"
                                      "    border: 1px solid #0078D7; /* Highlight border when clicked/focused */\n"
                                      "}\n"
                                      "")
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(parent=self.frame_6)
        self.lineEdit_10.setGeometry(QtCore.QRect(360, 150, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setStyleSheet("QLineEdit {\n"
                                       "    background-color: #FFFFFF; /* White background */\n"
                                       "    border: 1px solid #CCCCCC; /* Light grey border */\n"
                                       "    border-radius: 10px; /* Rounded corners (adjust as needed) */\n"
                                       "    padding: 8px; /* Space inside the box so text isn\'t touching edges */\n"
                                       "    box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.2); /* Dropdown shadow */\n"
                                       "}\n"
                                       "\n"
                                       "QLineEdit:focus {\n"
                                       "    border: 1px solid #0078D7; /* Highlight border when clicked/focused */\n"
                                       "}\n"
                                       "")
        self.lineEdit_10.setText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(parent=self.frame_6)
        self.lineEdit_11.setGeometry(QtCore.QRect(150, 200, 391, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setStyleSheet("QLineEdit {\n"
                                       "    background-color: #FFFFFF; /* White background */\n"
                                       "    border: 1px solid #CCCCCC; /* Light grey border */\n"
                                       "    border-radius: 10px; /* Rounded corners (adjust as needed) */\n"
                                       "    padding: 8px; /* Space inside the box so text isn\'t touching edges */\n"
                                       "    box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.2); /* Dropdown shadow */\n"
                                       "}\n"
                                       "\n"
                                       "QLineEdit:focus {\n"
                                       "    border: 1px solid #0078D7; /* Highlight border when clicked/focused */\n"
                                       "}\n"
                                       "")
        self.lineEdit_11.setText("")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.frame_6)
        self.pushButton_10.setGeometry(QtCore.QRect(170, 250, 351, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(99, 88, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(99, 88, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(99, 88, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(99, 88, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(99, 88, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(99, 88, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(99, 88, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(99, 88, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(99, 88, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        self.pushButton_10.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("QPushButton {\n"
                                         "    background-color: #6358DC;\n"
                                         "    border: none; /* Optional: Removes the default system border so the color shows fully */\n"
                                         "}\n"
                                         "QPushButton {\n"
                                         "    padding: 15px 32px; /* Add padding for a better size */\n"
                                         "    text-align: center;\n"
                                         "    text-decoration: none;\n"
                                         "    font-size: 10px;\n"
                                         "    margin: 4px 2px;\n"
                                         "    border-radius: 8px; /* Rounded corners */\n"
                                         "}\n"
                                         "QPushButton:hover {\n"
                                         "    background-color: #BF94E4; /* Darker green on hover */\n"
                                         "}\n"
                                         "")
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_10 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_10.setGeometry(QtCore.QRect(310, 40, 131, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        self.label_10.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.frame_5 = QtWidgets.QFrame(parent=self.MyProfile)
        self.frame_5.setGeometry(QtCore.QRect(20, 90, 151, 441))
        self.frame_5.setStyleSheet("\n"
                                   "background-color: rgb(217, 219, 221);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_9 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_9.setGeometry(QtCore.QRect(5, -10, 151, 111))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/images/logoremover.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.frame_5)
        self.pushButton_9.setGeometry(QtCore.QRect(0, 90, 151, 41))
        self.pushButton_9.setStyleSheet("/* Base style for the button */\n"
                                        "QPushButton {\n"
                                        "    /* Make the button transparent by default */\n"
                                        "  background-color: #transparent; /* The light grey color from the picture */\n"
                                        "    color: black;              /* Keeps the text black */\n"
                                        "    /* Adjust border-radius to match the full rounding in the image */\n"
                                        "    border-radius: 15px;       \n"
                                        "}\n"
                                        "/* The style to use when the button is the active page (the \"checked\" state) */\n"
                                        "")
        self.pushButton_9.setCheckable(True)
        self.pushButton_9.setChecked(False)
        self.pushButton_9.setObjectName("pushButton_9")
        self.logoutButton = QtWidgets.QPushButton(parent=self.frame_5)
        self.logoutButton.setGeometry(QtCore.QRect(0, 410, 151, 23))
        self.logoutButton.setStyleSheet("QPushButton {\n"
                                        "    background-color: transparent;\n"
                                        "    border: none;\n"
                                        "    color: red;\n"
                                        "}")
        self.logoutButton.setObjectName("logoutButton")
        self.MyAppointmentsButton = QtWidgets.QPushButton(parent=self.frame_5)
        self.MyAppointmentsButton.setGeometry(QtCore.QRect(0, 150, 151, 41))
        self.MyAppointmentsButton.setStyleSheet("/* Base style for the button */\n"
                                                "QPushButton {\n"
                                                "    /* Make the button transparent by default */\n"
                                                "  background-color: #transparent; /* The light grey color from the picture */\n"
                                                "    color: black;              /* Keeps the text black */\n"
                                                "    /* Adjust border-radius to match the full rounding in the image */\n"
                                                "    border-radius: 15px;       \n"
                                                "}\n"
                                                "/* The style to use when the button is the active page (the \"checked\" state) */\n"
                                                "")
        self.MyAppointmentsButton.setCheckable(True)
        self.MyAppointmentsButton.setChecked(False)
        self.MyAppointmentsButton.setObjectName("MyAppointmentsButton")
        self.pushButton_19 = QtWidgets.QPushButton(parent=self.frame_5)
        self.pushButton_19.setGeometry(QtCore.QRect(0, 210, 151, 41))
        self.pushButton_19.setStyleSheet("/* Base style for the button */\n"
                                         "QPushButton {\n"
                                         "    /* Make the button transparent by default */\n"
                                         "  background-color: #D3D3D3; /* The light grey color from the picture */\n"
                                         "    color: black;              /* Keeps the text black */\n"
                                         "    /* Adjust border-radius to match the full rounding in the image */\n"
                                         "    border-radius: 15px;       \n"
                                         "}\n"
                                         "/* The style to use when the button is the active page (the \"checked\" state) */\n"
                                         "")
        self.pushButton_19.setCheckable(True)
        self.pushButton_19.setChecked(False)
        self.pushButton_19.setObjectName("pushButton_19")
        self.stackedWidget.addWidget(self.MyProfile)
        self.stackedWidget.raise_()
        self.pushButton_6.raise_()
        self.label_5.raise_()
        self.pushButton_5.raise_()
        self.label_8.raise_()
        self.pushButton_4.raise_()
        Login.setCentralWidget(self.centralwidget)

        self.retranslateUi(Login)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "MainWindow"))
        self.label_8.setText(_translate("Login", "CARELINE"))
        self.pushButton_4.setText(_translate("Login", "Home"))
        self.pushButton_5.setText(_translate("Login", "About Us"))
        self.pushButton_6.setText(_translate("Login", "Contact Us"))
        self.NewAppointmentbutton.setText(_translate("Login", "New Appointment"))
        self.Logoutbutton.setText(_translate("Login", "Log Out"))
        self.MyAppointmentbutton.setText(_translate("Login", "My Appointments"))
        self.pushButton_13.setText(_translate("Login", "My Profile"))
        self.textDrLevi_2.setText(_translate("Login", "Dr. Levi"))
        self.textDrLevi.setText(_translate("Login", "Dentist"))
        self.textDrChancee.setText(_translate("Login", "Dr. Chi"))
        self.textDrChancee_2.setText(_translate("Login", "Psych"))
        self.saveappointment.setText(_translate("Login", "Save Appointment"))
        self.NewAppointmentbutton_2.setText(_translate("Login", "New Appointment"))
        self.LogOutButton.setText(_translate("Login", "Log Out"))
        self.MyAppointmentButton.setText(_translate("Login", "My Appointments"))
        self.MyProfileButton.setText(_translate("Login", "My Profile"))
        self.label_2.setText(_translate("Login", "My Appointments"))
        item = self.MyAppointments_3.horizontalHeaderItem(0)
        item.setText(_translate("Login", "Date"))
        item = self.MyAppointments_3.horizontalHeaderItem(1)
        item.setText(_translate("Login", "Time"))
        item = self.MyAppointments_3.horizontalHeaderItem(2)
        item.setText(_translate("Login", "Doctor"))
        self.lineEdit_7.setPlaceholderText(_translate("Login", "Account First Name"))
        self.lineEdit_8.setPlaceholderText(_translate("Login", "Account Last Name"))
        self.lineEdit_9.setPlaceholderText(_translate("Login", "Account Phone Number"))
        self.lineEdit_10.setPlaceholderText(_translate("Login", "Account Email"))
        self.lineEdit_11.setPlaceholderText(_translate("Login", "Address"))
        self.pushButton_10.setText(_translate("Login", "Save Changes"))
        self.label_10.setText(_translate("Login", "My Profile"))
        self.pushButton_9.setText(_translate("Login", "New Appointment"))
        self.logoutButton.setText(_translate("Login", "Log Out"))
        self.MyAppointmentsButton.setText(_translate("Login", "My Appointments"))
        self.pushButton_19.setText(_translate("Login", "My Profile"))


